### ISSUE TITLE
Release new Dockerhub image

### ISSUE THREAD

**Issue by OscarVanL** [ossillate-inc/packj#102]
**Is your feature request related to a problem? Please describe.**
I am encountering the (fixed) bug described [here](https://github.com/ossillate-inc/packj/issues/93) using `ossillate/packj:latest
` from Dockerhub. It appears the docker container was released 10 months ago, but the fix was released after.

**Describe the solution you'd like**
Please can you release a new version and push this to dockerhub?

**Describe alternatives you've considered**
Building myself and not using the docker container, however, the docker approach is the "recommended" way of running packj according to the README, so it should probably be updated instead.

**Additional context**
The error I am encountering:
```
Failed to dump json content to file /tmp/packj/packj_audit_z5zkn9zd/report_mnplwltk.json: Object of type Commit is not JSON serializable
```

**Comment by ashishbijlani** [comment]
Updated the docker image. Thanks for reporting!

**Comment by OscarVanL** [comment]
Thank you!

**Comment by digital2real** [comment]
Hello,
Do you plan to release updated docker images ?
