### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by R9295** [ossillate-inc/packj#15]
Hello,

Cool project! I wanted to see how I could contribute but could not join the discord due to the invalid invite link.
![image](https://user-images.githubusercontent.com/15076206/203088388-88a85838-6079-4c18-9c60-6aa2a14b3782.png)

**Comment by ashishbijlani** [comment]
Thanks so much for noticing this! I've fixed the invite link; you can try now. We welcome all code contributions: adding new language (e.g., rust) support, developing IDE or CI/CD plugins. Please DM me and I'd be happy to discuss/guide you.
