### ISSUE TITLE
Add version option

### ISSUE THREAD

**Issue by S30tt** [ossillate-inc/packj#27]
**Is your feature request related to a problem? Please describe.**
No, this is a new feature.

**Describe the solution you'd like**
When running packj -v or packj --version it will display the version number of the tool.  

**Describe alternatives you've considered**
Passing a random string as the command to the tool returns and error.  The prefix of the error is the app version string.  I am considering parsing this but a dedicated command -v --version would be more standard.

**Comment by ashishbijlani** [comment]
Thanks! Commit [6e7eca8](https://github.com/ossillate-inc/packj/commit/6e7eca8a2f4173e685bc5f79e32d54a5da7229e5) takes care of this.
