### ISSUE TITLE
Detection capability for local Node.js projects

### ISSUE THREAD

**Issue by werifu** [ossillate-inc/packj#32]
**Is your feature request related to a problem? Please describe.**
I'm doing some research about supply chain attacks happened in the ecosystem of Node.js and I use packj to analyze malicious samples which have been removed from npmjs's official registry.

Actually, there are also other occasions when developers want to analyze some packages that not managed on the official registry. For example, some Node.js applications that directly released on GitHub. Therefore, capability to detect malicious behavior for local projects are also beneficial.

**Describe the solution you'd like**
I hope I can use the following command to audit a local project
```bash
$python3 main.py audit -p npm:/path/to/node/project
```

**Describe alternatives you've considered**
I'm refactoring the **pm_proxy** of  npmjs in my forked repo in order to support the capability of local analysis.

**Additional context**
If you think it a good idea, we can discuss further more in this issue and I'm willing to contribute for the local detection capability on js. If you are not interested in this new feature, it's ok for me and I will just modify the code to fit only my specific needs.

**Comment by ashishbijlani** [comment]
Absolutely! I agree that this is a useful feature request. Would love to work with you on this and integrate into Packj. It'd be grate if you could join the Discord channel so that we can easily communicate. Thanks so much!

**Comment by ashishbijlani** [comment]
May be introduce an option in .packj.yaml file for entering the registry URL and modifying the code to use this in pm_proxy Packj can work with private registry by first creating an ID in .packj.yaml (e.g., currently pypi: https://pypi.org/, future local-pypi: https://localhost:8000/) and then specifying the registry ID (e.g., packj audit -p local-pypi:deleted-package-name)

**Comment by werifu** [comment]
have been merged at
https://github.com/ossillate-inc/packj/pull/33
