### ISSUE TITLE
[+] Fetching 'browserify' from npm..........FAIL [package not found!]

### ISSUE THREAD

**Issue by HangShuLYH** [ossillate-inc/packj#40]
When I run:
python3 main.py audit -p npm:browserify --debug

Get Following output:
*** NOTE: Running in debug mode (log: /tmp/packj_audit_bwbde3qu/debug_kzpj3kik.log) ***

===============================================
Auditing npm package browserify (ver: latest)
===============================================
[+] Fetching 'browserify' from npm..........FAIL [package not found!]
=============================================
=> HTML summary available at: /tmp/packj_audit_bwbde3qu/report_stsfndao.html

/tmp/packj_audit_bwbde3qu/debug_kzpj3kik.log:
09:47:25,568 root DEBUG fail in get_metadata for pkg browserify: Failed to parse: https://registry.npmjs.org/browserify

/tmp/packj_audit_bwbde3qu/report_stsfndao.html:

<!DOCTYPE html>
<html>
<head>
	<title>
		Packj security audit report
	</title>
</head>
<body>
	<div>
		<h4><a href="https://github.com/ossillate-inc/packj" target="_blank">Packj</a> audit found 0/0 risky dependencies.</h4>
	</div>
	<details>
		<summary><h4>Click here for details</h4></summary>
		<table style="border-style: solid; border-width: thin;">
			<tr>
				<th>Registry</th>
				<th>Package</th>
				<th>Version</th>
				<th>Risks</th>
			</tr>
			
		</table>
	</details>
</body>
</html>

**Comment by ashishbijlani** [comment]
Cannot reproduce the issue. For me Packj works fine and is able to download `browserify` package from NPM registry. Are you behind a proxy or working with a private NPM mirror (check ~/.npmrc file)?
