### ISSUE TITLE
[Feature]: Scoring package while auditing the package.

### ISSUE THREAD

**Issue by shivaabhishek07** [ossillate-inc/packj#68]
Recently, OpenSSF introduced a `scorecard`, which gives a score to each package. 

How about we give the score to each package that we analyze and include that score in the final report?

**Comment by ashishbijlani** [comment]
The reason Packj doesn't assign generic scores is because such numbers would have different meaning to different users. For example, absence of source repo may be assigned different scores based on the perceived threat.
