### ISSUE TITLE
Analysis of the Tracing Log

### ISSUE THREAD

**Issue by Co1lin** [ossillate-inc/packj#87]
First, thanks for the amazing work!

I want to check my understanding of the current implementation of tracing. If we specify `-t`, the installation will be traced with `strace -f -ttt -T -o strace.log <cmd>`. Then the tracing log will be parsed by [parse_trace_file](https://github.com/ossillate-inc/packj/blob/fd77af029505a7aa0d19fba555b3c17133a9c987/packj/audit/parse_strace.py#L67). If the parsing succeed, an [OK message](https://github.com/ossillate-inc/packj/blob/fd77af029505a7aa0d19fba555b3c17133a9c987/packj/audit/main.py#L872) would appear with a brief summary of syscalls.

To me, it seems that the tracing log is only "parsed", but not "analyzed". So if some suspicious activities are logged into the tracing log, it will still report an OK message. Then, a manual analysis of the tracing log is required to draw a conclusion of whether it is malicious or not. Is it correct?

BTW, the current version does not support tracing for local packages. I find it only requires a few lines of changes to support tracing `local_nodejs:/path/to/pkg`. Is there anyone working on this? I can propose a PR if needed.

**Comment by ashishbijlani** [comment]
Yes, your understanding is correct. More work is needed for analyzing parsed logs for suspicious activities. Feel free to submit a PR. Thanks!
