### ISSUE TITLE
Failed to dump json content to file: Object of type Commit is not JSON serializable

### ISSUE THREAD

**Issue by Jane-Hopp** [ossillate-inc/packj#93]
**Describe the bug**
When auditing a package I always get the message:
Failed to dump json content to file /tmp/report_file_name.json: Object of type Commit is not JSON serializable.

**To Reproduce**
1. Execute the command:
`docker run -v /tmp:/tmp/packj -it ossillate/packj:latest audit --trace -p npm:browserify
`
3. Look at the end of the report
4. See error:
`Failed to dump json content to file /tmp/packj/packj_audit_xw3c332_/report_4fa1somg.json: Object of type Commit is not JSON serializable`

**Expected behavior**
There should be a report in JSON format listing the reasons why the package is undesirable.
Like this:
`=> Complete report: /tmp/packj_54rbjhgm/report_npm-browserify-17.0.0_hlr1rhcz.json`
`{`
`    "undesirable": [`
`        "old package: 702 days old",`
`        "invalid or no author email: expired author email domain",`
`        "generates new code at runtime",`
`        "reads files and dirs",`
`        "forks or exits OS processes",`
`    ]`
`}`

**Screenshots**
Error message:
![error_message](https://github.com/ossillate-inc/packj/assets/110847984/11b0655d-bb6a-4483-9870-ddcfb8eac87c)

**Additional context**
1. I found that the JSON report files are incorrect. For example:
![incorrect_json_file](https://github.com/ossillate-inc/packj/assets/110847984/8084e7fb-33b7-459f-9c43-bc2c7ebc9e0c)

2. The same error appears when I run the program [without using docker](https://github.com/ossillate-inc/packj#3-source-repo).

**Comment by ashishbijlani** [comment]
Thanks! Looks like commit objects need to be serialized. Would love to receive a FIX on the issue from you.

**Comment by KyeRussell** [comment]
FWIW for whoever picks this up (if not me): when looking into this, I've noticed that Packj also sometimes attempts to serialize `set`, which the default standard library JSON encoder does not serialize.
